import { db } from "./firebase.js";
import { collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/12.5.0/firebase-firestore.js";
const CLOUD_NAME="wf6ocs3j", UPLOAD_PRESET="kts_members";
const ref=collection(db,"galleryGroups");
const heading=document.getElementById("galleryHeading"), caption=document.getElementById("galleryCaption"), fileInput=document.getElementById("galleryPhotoFile"), count=document.getElementById("gallerySelectedCount"), preview=document.getElementById("galleryPreviewBox"), existingBox=document.getElementById("galleryExistingPhotos"), saveBtn=document.getElementById("saveGalleryBtn"), cancelBtn=document.getElementById("cancelGalleryEditBtn"), list=document.getElementById("adminGalleryList"), formTitle=document.getElementById("galleryFormTitle");
let selected=[], editingId=null, keptPhotos=[];
fileInput?.addEventListener("change",()=>{selected=Array.from(fileInput.files); count.textContent=selected.length?`${selected.length}টি নতুন ছবি নির্বাচন করা হয়েছে`:"কোনো নতুন ছবি নির্বাচন করা হয়নি"; preview.innerHTML=""; selected.forEach(f=>{const i=document.createElement("img");i.src=URL.createObjectURL(f);i.className="admin-gallery-thumb";preview.appendChild(i);});});
async function upload(file){const fd=new FormData();fd.append("file",file);fd.append("upload_preset",UPLOAD_PRESET);const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/upload`,{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Upload failed");return {url:d.secure_url,publicId:d.public_id};}
saveBtn?.addEventListener("click",async()=>{const h=heading.value.trim(),c=caption.value.trim();if(!h)return alert("Heading লিখুন");if(!editingId&&!selected.length)return alert("অন্তত একটি ছবি নির্বাচন করুন");try{saveBtn.disabled=true;const uploaded=[];for(let i=0;i<selected.length;i++){saveBtn.textContent=`📤 Upload ${i+1}/${selected.length}`;uploaded.push(await upload(selected[i]));}const photos=[...keptPhotos,...uploaded];if(editingId){await updateDoc(doc(db,"galleryGroups",editingId),{heading:h,caption:c,photos,updatedAt:serverTimestamp()});alert("✅ Gallery Group Update হয়েছে");}else{await addDoc(ref,{heading:h,caption:c,photos,createdAt:serverTimestamp()});alert("✅ Gallery Group তৈরি হয়েছে");}clearForm();}catch(e){console.error(e);alert("❌ Save হয়নি: "+e.message);}finally{saveBtn.disabled=false;if(!editingId)saveBtn.textContent="📤 Gallery Group Upload করুন";}});
const q=query(ref,orderBy("createdAt","desc"));
onSnapshot(q,s=>{list.innerHTML="";if(s.empty){list.innerHTML="<p>কোনো Gallery Group নেই।</p>";return;}s.forEach(x=>{const d=x.data(), card=document.createElement("div");card.className="admin-gallery-group";card._data={id:x.id,...d};card.innerHTML=`<h3>${safe(d.heading)}</h3><p>${safe(d.caption||"")}</p><div class="admin-gallery-thumbs">${(d.photos||[]).map(p=>`<img src="${p.url}" class="admin-gallery-thumb">`).join("")}</div><div class="admin-gallery-actions"><button class="edit-gallery-group-btn">✏️ Edit</button><button class="delete-gallery-group-btn">🗑️ Delete</button></div><hr>`;list.appendChild(card);});});
document.addEventListener("click",async e=>{const eb=e.target.closest(".edit-gallery-group-btn");if(eb){const d=eb.closest(".admin-gallery-group")._data;editingId=d.id;keptPhotos=[...(d.photos||[])];heading.value=d.heading||"";caption.value=d.caption||"";selected=[];fileInput.value="";preview.innerHTML="";renderExisting();formTitle.textContent="✏️ Gallery Group Edit করুন";saveBtn.textContent="💾 Update করুন";cancelBtn.style.display="inline-block";document.getElementById("galleryPage")?.scrollIntoView({behavior:"smooth"});return;}const rb=e.target.closest(".remove-existing-photo");if(rb){keptPhotos.splice(Number(rb.dataset.index),1);renderExisting();return;}const dbtn=e.target.closest(".delete-gallery-group-btn");if(dbtn){const d=dbtn.closest(".admin-gallery-group")._data;if(!confirm(`“${d.heading}” পুরো Group Delete করবেন?`))return;try{await deleteDoc(doc(db,"galleryGroups",d.id));if(editingId===d.id)clearForm();alert("✅ Delete হয়েছে");}catch(err){alert("❌ Delete হয়নি: "+err.message);}}});
cancelBtn?.addEventListener("click",clearForm);
function renderExisting(){existingBox.innerHTML=keptPhotos.length?`<p>বর্তমান ছবি (যেটা বাদ দিতে চান × চাপুন):</p><div class="admin-gallery-thumbs">${keptPhotos.map((p,i)=>`<div class="existing-photo-wrap"><img src="${p.url}" class="admin-gallery-thumb"><button type="button" class="remove-existing-photo" data-index="${i}">×</button></div>`).join("")}</div>`:"";}
function clearForm(){heading.value="";caption.value="";fileInput.value="";selected=[];editingId=null;keptPhotos=[];count.textContent="কোনো ছবি নির্বাচন করা হয়নি";preview.innerHTML="";existingBox.innerHTML="";formTitle.textContent="➕ নতুন Gallery Group তৈরি করুন";saveBtn.textContent="📤 Gallery Group Upload করুন";cancelBtn.style.display="none";}
function safe(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
